### ISSUE TITLE
Error: Command "prepare-release" is not defined.

### ISSUE THREAD

**Issue by christophlehmann** [tomasnorre/typo3-upload-ter#11]
Since 23. Juli i get the error

```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "prepare-release" is not defined. 
 ```

Two releases before that date worked fine. How to fix it?

**Comment by tomasnorre** [comment]
Thanks for reporting the problem. 

As there are no changes in the TYPO3 TER Uploader for quite some time. 

I think it's related to a symfony update in your extension. 

You can fix this by adding a prepare-release to you script section in composer, see the README.md
https://github.com/tomasnorre/typo3-upload-ter#recommendation

If you don't need the section, you can leave the echo something instead of the suggested commands.

I'll check if I can fix this properly.

**Comment by tomasnorre** [comment]
This has been done for quite some time, but for some reason never closed. 
Thanks, @christophlehmann, for fixing this.
